#!/bin/bash

# generacion de datos para validarlos en C de la Construccion de Maxwell

cd ../../sUpVdW

# Ingresando en cuda
cd cuda

#Creacion de carpetas para datos de los bloque

mkdir 1B 2B 4B 8B 16B 32B 64B 128B 256B 512B

cd 1B

{
    # Creacion de carpetas para el tamaño de bloque
    # Sólo quedará el archivo con el tiempo

    mkdir 16 32 64 128 256 512 1024 2048 4096

    cd 16
    ln -s ../../../InitialParameters.txt .
    latticeBox2D 3 16 periodicX
    cudaVdWColumnHT 50000 50100 1 >&datos
    rm -rf lattice* f* g* h* T* U*  rho* *.case

    cd ../32
    ln -s ../../../InitialParameters.txt .
    latticeBox2D 3 32 periodicX
    cudaVdWColumnHT 50000 50100 1 >&datos
    rm -rf lattice* f* g* h* T* U*  rho* *.case

    cd ../64
    ln -s ../../../InitialParameters.txt .
    latticeBox2D 3 64 periodicX
    cudaVdWColumnHT 50000 50100 1 >&datos
    rm -rf lattice* f* g* h* T* U*  rho* *.case

    cd ../128
    ln -s ../../../InitialParameters.txt .
    latticeBox2D 3 128 periodicX
    cudaVdWColumnHT 50000 50100 1 >&datos
    rm -rf lattice* f* g* h* T* U*  rho* *.case

    cd ../256
    ln -s ../../../InitialParameters.txt .
    latticeBox2D 3 256 periodicX
    cudaVdWColumnHT 50000 50100 1 >&datos
    rm -rf lattice* f* g* h* T* U*  rho* *.case

    cd ../512
    ln -s ../../../InitialParameters.txt .
    latticeBox2D 3 512 periodicX
    cudaVdWColumnHT 50000 50100 1 >&datos
    rm -rf lattice* f* g* h* T* U*  rho* *.case

    cd ../1024
    ln -s ../../../InitialParameters.txt .
    latticeBox2D 3 1024 periodicX
    cudaVdWColumnHT 50000 50100 1 >&datos
    rm -rf lattice* f* g* h* T* U*  rho* *.case

    cd ../2048
    ln -s ../../../InitialParameters.txt .
    latticeBox2D 3 2048 periodicX
    cudaVdWColumnHT 50000 50100 1 >&datos
    rm -rf lattice* f* g* h* T* U*  rho* *.case

    cd ../4096
    ln -s ../../../InitialParameters.txt .
    latticeBox2D 3 4096 periodicX
    cudaVdWColumnHT 50000 50100 1 >&datos
    rm -rf lattice* f* g* h* T* U*  rho* *.case

    # Posicionamiento en cuda
    cd ../../

}

echo Done Block

cd 2B

{
    # Creacion de carpetas para el tamaño de bloque
    # Sólo quedará el archivo con el tiempo

    mkdir 16 32 64 128 256 512 1024 2048 4096

    cd 16
    ln -s ../../../InitialParameters.txt .
    latticeBox2D 3 16 periodicX
    cudaVdWColumnHT 50000 50100 2 >&datos
    rm -rf lattice* f* g* h* T* U*  rho* *.case

    cd ../32
    ln -s ../../../InitialParameters.txt .
    latticeBox2D 3 32 periodicX
    cudaVdWColumnHT 50000 50100 2 >&datos
    rm -rf lattice* f* g* h* T* U*  rho* *.case

    cd ../64
    ln -s ../../../InitialParameters.txt .
    latticeBox2D 3 64 periodicX
    cudaVdWColumnHT 50000 50100 2 >&datos
    rm -rf lattice* f* g* h* T* U*  rho* *.case

    cd ../128
    ln -s ../../../InitialParameters.txt .
    latticeBox2D 3 128 periodicX
    cudaVdWColumnHT 50000 50100 2 >&datos
    rm -rf lattice* f* g* h* T* U*  rho* *.case

    cd ../256
    ln -s ../../../InitialParameters.txt .
    latticeBox2D 3 256 periodicX
    cudaVdWColumnHT 50000 50100 2 >&datos
    rm -rf lattice* f* g* h* T* U*  rho* *.case

    cd ../512
    ln -s ../../../InitialParameters.txt .
    latticeBox2D 3 512 periodicX
    cudaVdWColumnHT 50000 50100 2 >&datos
    rm -rf lattice* f* g* h* T* U*  rho* *.case

    cd ../1024
    ln -s ../../../InitialParameters.txt .
    latticeBox2D 3 1024 periodicX
    cudaVdWColumnHT 50000 50100 2 >&datos
    rm -rf lattice* f* g* h* T* U*  rho* *.case

    cd ../2048
    ln -s ../../../InitialParameters.txt .
    latticeBox2D 3 2048 periodicX
    cudaVdWColumnHT 50000 50100 2 >&datos
    rm -rf lattice* f* g* h* T* U*  rho* *.case

    cd ../4096
    ln -s ../../../InitialParameters.txt .
    latticeBox2D 3 4096 periodicX
    cudaVdWColumnHT 50000 50100 2 >&datos
    rm -rf lattice* f* g* h* T* U*  rho* *.case

    # Posicionamiento en cuda
    cd ../../

}

echo Done Block

cd 4B

{
    # Creacion de carpetas para el tamaño de bloque
    # Sólo quedará el archivo con el tiempo

    mkdir 16 32 64 128 256 512 1024 2048 4096

    cd 16
    ln -s ../../../InitialParameters.txt .
    latticeBox2D 3 16 periodicX
    cudaVdWColumnHT 50000 50100 4 >&datos
    rm -rf lattice* f* g* h* T* U*  rho* *.case

    cd ../32
    ln -s ../../../InitialParameters.txt .
    latticeBox2D 3 32 periodicX
    cudaVdWColumnHT 50000 50100 4 >&datos
    rm -rf lattice* f* g* h* T* U*  rho* *.case

    cd ../64
    ln -s ../../../InitialParameters.txt .
    latticeBox2D 3 64 periodicX
    cudaVdWColumnHT 50000 50100 4 >&datos
    rm -rf lattice* f* g* h* T* U*  rho* *.case

    cd ../128
    ln -s ../../../InitialParameters.txt .
    latticeBox2D 3 128 periodicX
    cudaVdWColumnHT 50000 50100 4 >&datos
    rm -rf lattice* f* g* h* T* U*  rho* *.case

    cd ../256
    ln -s ../../../InitialParameters.txt .
    latticeBox2D 3 256 periodicX
    cudaVdWColumnHT 50000 50100 4 >&datos
    rm -rf lattice* f* g* h* T* U*  rho* *.case

    cd ../512
    ln -s ../../../InitialParameters.txt .
    latticeBox2D 3 512 periodicX
    cudaVdWColumnHT 50000 50100 4 >&datos
    rm -rf lattice* f* g* h* T* U*  rho* *.case

    cd ../1024
    ln -s ../../../InitialParameters.txt .
    latticeBox2D 3 1024 periodicX
    cudaVdWColumnHT 50000 50100 4 >&datos
    rm -rf lattice* f* g* h* T* U*  rho* *.case

    cd ../2048
    ln -s ../../../InitialParameters.txt .
    latticeBox2D 3 2048 periodicX
    cudaVdWColumnHT 50000 50100 4 >&datos
    rm -rf lattice* f* g* h* T* U*  rho* *.case

    cd ../4096
    ln -s ../../../InitialParameters.txt .
    latticeBox2D 3 4096 periodicX
    cudaVdWColumnHT 50000 50100 4 >&datos
    rm -rf lattice* f* g* h* T* U*  rho* *.case

    # Posicionamiento en cuda
    cd ../../

}

echo Done Block

cd 8B

{
    # Creacion de carpetas para el tamaño de bloque
    # Sólo quedará el archivo con el tiempo

    mkdir 16 32 64 128 256 512 1024 2048 4096

    cd 16
    ln -s ../../../InitialParameters.txt .
    latticeBox2D 3 16 periodicX
    cudaVdWColumnHT 50000 50100 8 >&datos
    rm -rf lattice* f* g* h* T* U*  rho* *.case

    cd ../32
    ln -s ../../../InitialParameters.txt .
    latticeBox2D 3 32 periodicX
    cudaVdWColumnHT 50000 50100 8 >&datos
    rm -rf lattice* f* g* h* T* U*  rho* *.case

    cd ../64
    ln -s ../../../InitialParameters.txt .
    latticeBox2D 3 64 periodicX
    cudaVdWColumnHT 50000 50100 8 >&datos
    rm -rf lattice* f* g* h* T* U*  rho* *.case

    cd ../128
    ln -s ../../../InitialParameters.txt .
    latticeBox2D 3 128 periodicX
    cudaVdWColumnHT 50000 50100 8 >&datos
    rm -rf lattice* f* g* h* T* U*  rho* *.case

    cd ../256
    ln -s ../../../InitialParameters.txt .
    latticeBox2D 3 256 periodicX
    cudaVdWColumnHT 50000 50100 8 >&datos
    rm -rf lattice* f* g* h* T* U*  rho* *.case

    cd ../512
    ln -s ../../../InitialParameters.txt .
    latticeBox2D 3 512 periodicX
    cudaVdWColumnHT 50000 50100 8 >&datos
    rm -rf lattice* f* g* h* T* U*  rho* *.case

    cd ../1024
    ln -s ../../../InitialParameters.txt .
    latticeBox2D 3 1024 periodicX
    cudaVdWColumnHT 50000 50100 8 >&datos
    rm -rf lattice* f* g* h* T* U*  rho* *.case

    cd ../2048
    ln -s ../../../InitialParameters.txt .
    latticeBox2D 3 2048 periodicX
    cudaVdWColumnHT 50000 50100 8 >&datos
    rm -rf lattice* f* g* h* T* U*  rho* *.case

    cd ../4096
    ln -s ../../../InitialParameters.txt .
    latticeBox2D 3 4096 periodicX
    cudaVdWColumnHT 50000 50100 8 >&datos
    rm -rf lattice* f* g* h* T* U*  rho* *.case

    # Posicionamiento en cuda
    cd ../../

}

echo Done Block

cd 16B

{
    # Creacion de carpetas para el tamaño de bloque
    # Sólo quedará el archivo con el tiempo

    mkdir 16 32 64 128 256 512 1024 2048 4096

    cd 16
    ln -s ../../../InitialParameters.txt .
    latticeBox2D 3 16 periodicX
    cudaVdWColumnHT 50000 50100 16 >&datos
    rm -rf lattice* f* g* h* T* U*  rho* *.case

    cd ../32
    ln -s ../../../InitialParameters.txt .
    latticeBox2D 3 32 periodicX
    cudaVdWColumnHT 50000 50100 16 >&datos
    rm -rf lattice* f* g* h* T* U*  rho* *.case

    cd ../64
    ln -s ../../../InitialParameters.txt .
    latticeBox2D 3 64 periodicX
    cudaVdWColumnHT 50000 50100 16 >&datos
    rm -rf lattice* f* g* h* T* U*  rho* *.case

    cd ../128
    ln -s ../../../InitialParameters.txt .
    latticeBox2D 3 128 periodicX
    cudaVdWColumnHT 50000 50100 16 >&datos
    rm -rf lattice* f* g* h* T* U*  rho* *.case

    cd ../256
    ln -s ../../../InitialParameters.txt .
    latticeBox2D 3 256 periodicX
    cudaVdWColumnHT 50000 50100 16 >&datos
    rm -rf lattice* f* g* h* T* U*  rho* *.case

    cd ../512
    ln -s ../../../InitialParameters.txt .
    latticeBox2D 3 512 periodicX
    cudaVdWColumnHT 50000 50100 16 >&datos
    rm -rf lattice* f* g* h* T* U*  rho* *.case

    cd ../1024
    ln -s ../../../InitialParameters.txt .
    latticeBox2D 3 1024 periodicX
    cudaVdWColumnHT 50000 50100 16 >&datos
    rm -rf lattice* f* g* h* T* U*  rho* *.case

    cd ../2048
    ln -s ../../../InitialParameters.txt .
    latticeBox2D 3 2048 periodicX
    cudaVdWColumnHT 50000 50100 16 >&datos
    rm -rf lattice* f* g* h* T* U*  rho* *.case

    cd ../4096
    ln -s ../../../InitialParameters.txt .
    latticeBox2D 3 4096 periodicX
    cudaVdWColumnHT 50000 50100 16 >&datos
    rm -rf lattice* f* g* h* T* U*  rho* *.case

    # Posicionamiento en cuda
    cd ../../

}

echo Done Block

cd 32B

{
    # Creacion de carpetas para el tamaño de bloque
    # Sólo quedará el archivo con el tiempo

    mkdir 16 32 64 128 256 512 1024 2048 4096

    cd 16
    ln -s ../../../InitialParameters.txt .
    latticeBox2D 3 16 periodicX
    cudaVdWColumnHT 50000 50100 32 >&datos
    rm -rf lattice* f* g* h* T* U*  rho* *.case

    cd ../32
    ln -s ../../../InitialParameters.txt .
    latticeBox2D 3 32 periodicX
    cudaVdWColumnHT 50000 50100 32 >&datos
    rm -rf lattice* f* g* h* T* U*  rho* *.case

    cd ../64
    ln -s ../../../InitialParameters.txt .
    latticeBox2D 3 64 periodicX
    cudaVdWColumnHT 50000 50100 32 >&datos
    rm -rf lattice* f* g* h* T* U*  rho* *.case

    cd ../128
    ln -s ../../../InitialParameters.txt .
    latticeBox2D 3 128 periodicX
    cudaVdWColumnHT 50000 50100 32 >&datos
    rm -rf lattice* f* g* h* T* U*  rho* *.case

    cd ../256
    ln -s ../../../InitialParameters.txt .
    latticeBox2D 3 256 periodicX
    cudaVdWColumnHT 50000 50100 32 >&datos
    rm -rf lattice* f* g* h* T* U*  rho* *.case

    cd ../512
    ln -s ../../../InitialParameters.txt .
    latticeBox2D 3 512 periodicX
    cudaVdWColumnHT 50000 50100 32 >&datos
    rm -rf lattice* f* g* h* T* U*  rho* *.case

    cd ../1024
    ln -s ../../../InitialParameters.txt .
    latticeBox2D 3 1024 periodicX
    cudaVdWColumnHT 50000 50100 32 >&datos
    rm -rf lattice* f* g* h* T* U*  rho* *.case

    cd ../2048
    ln -s ../../../InitialParameters.txt .
    latticeBox2D 3 2048 periodicX
    cudaVdWColumnHT 50000 50100 32 >&datos
    rm -rf lattice* f* g* h* T* U*  rho* *.case

    cd ../4096
    ln -s ../../../InitialParameters.txt .
    latticeBox2D 3 4096 periodicX
    cudaVdWColumnHT 50000 50100 32 >&datos
    rm -rf lattice* f* g* h* T* U*  rho* *.case

    # Posicionamiento en cuda
    cd ../../

}

echo Done Block

cd 64B

{
    # Creacion de carpetas para el tamaño de bloque
    # Sólo quedará el archivo con el tiempo

    mkdir 16 32 64 128 256 512 1024 2048 4096

    cd 16
    ln -s ../../../InitialParameters.txt .
    latticeBox2D 3 16 periodicX
    cudaVdWColumnHT 50000 50100 64 >&datos
    rm -rf lattice* f* g* h* T* U*  rho* *.case

    cd ../32
    ln -s ../../../InitialParameters.txt .
    latticeBox2D 3 32 periodicX
    cudaVdWColumnHT 50000 50100 64 >&datos
    rm -rf lattice* f* g* h* T* U*  rho* *.case

    cd ../64
    ln -s ../../../InitialParameters.txt .
    latticeBox2D 3 64 periodicX
    cudaVdWColumnHT 50000 50100 64 >&datos
    rm -rf lattice* f* g* h* T* U*  rho* *.case

    cd ../128
    ln -s ../../../InitialParameters.txt .
    latticeBox2D 3 128 periodicX
    cudaVdWColumnHT 50000 50100 64 >&datos
    rm -rf lattice* f* g* h* T* U*  rho* *.case

    cd ../256
    ln -s ../../../InitialParameters.txt .
    latticeBox2D 3 256 periodicX
    cudaVdWColumnHT 50000 50100 64 >&datos
    rm -rf lattice* f* g* h* T* U*  rho* *.case

    cd ../512
    ln -s ../../../InitialParameters.txt .
    latticeBox2D 3 512 periodicX
    cudaVdWColumnHT 50000 50100 64 >&datos
    rm -rf lattice* f* g* h* T* U*  rho* *.case

    cd ../1024
    ln -s ../../../InitialParameters.txt .
    latticeBox2D 3 1024 periodicX
    cudaVdWColumnHT 50000 50100 64 >&datos
    rm -rf lattice* f* g* h* T* U*  rho* *.case

    cd ../2048
    ln -s ../../../InitialParameters.txt .
    latticeBox2D 3 2048 periodicX
    cudaVdWColumnHT 50000 50100 64 >&datos
    rm -rf lattice* f* g* h* T* U*  rho* *.case

    cd ../4096
    ln -s ../../../InitialParameters.txt .
    latticeBox2D 3 4096 periodicX
    cudaVdWColumnHT 50000 50100 64 >&datos
    rm -rf lattice* f* g* h* T* U*  rho* *.case

    # Posicionamiento en cuda
    cd ../../

}

echo Done Block

cd 128B

{
    # Creacion de carpetas para el tamaño de bloque
    # Sólo quedará el archivo con el tiempo

    mkdir 16 32 64 128 256 512 1024 2048 4096

    cd 16
    ln -s ../../../InitialParameters.txt .
    latticeBox2D 3 16 periodicX
    cudaVdWColumnHT 50000 50100 128 >&datos
    rm -rf lattice* f* g* h* T* U*  rho* *.case

    cd ../32
    ln -s ../../../InitialParameters.txt .
    latticeBox2D 3 32 periodicX
    cudaVdWColumnHT 50000 50100 128 >&datos
    rm -rf lattice* f* g* h* T* U*  rho* *.case

    cd ../64
    ln -s ../../../InitialParameters.txt .
    latticeBox2D 3 64 periodicX
    cudaVdWColumnHT 50000 50100 128 >&datos
    rm -rf lattice* f* g* h* T* U*  rho* *.case

    cd ../128
    ln -s ../../../InitialParameters.txt .
    latticeBox2D 3 128 periodicX
    cudaVdWColumnHT 50000 50100 128 >&datos
    rm -rf lattice* f* g* h* T* U*  rho* *.case

    cd ../256
    ln -s ../../../InitialParameters.txt .
    latticeBox2D 3 256 periodicX
    cudaVdWColumnHT 50000 50100 128 >&datos
    rm -rf lattice* f* g* h* T* U*  rho* *.case

    cd ../512
    ln -s ../../../InitialParameters.txt .
    latticeBox2D 3 512 periodicX
    cudaVdWColumnHT 50000 50100 128 >&datos
    rm -rf lattice* f* g* h* T* U*  rho* *.case

    cd ../1024
    ln -s ../../../InitialParameters.txt .
    latticeBox2D 3 1024 periodicX
    cudaVdWColumnHT 50000 50100 128 >&datos
    rm -rf lattice* f* g* h* T* U*  rho* *.case

    cd ../2048
    ln -s ../../../InitialParameters.txt .
    latticeBox2D 3 2048 periodicX
    cudaVdWColumnHT 50000 50100 128 >&datos
    rm -rf lattice* f* g* h* T* U*  rho* *.case

    cd ../4096
    ln -s ../../../InitialParameters.txt .
    latticeBox2D 3 4096 periodicX
    cudaVdWColumnHT 50000 50100 128 >&datos
    rm -rf lattice* f* g* h* T* U*  rho* *.case

    # Posicionamiento en cuda
    cd ../../

}

echo Done Block

cd 256B

{
    # Creacion de carpetas para el tamaño de bloque
    # Sólo quedará el archivo con el tiempo

    mkdir 16 32 64 128 256 512 1024 2048 4096

    cd 16
    ln -s ../../../InitialParameters.txt .
    latticeBox2D 3 16 periodicX
    cudaVdWColumnHT 50000 50100 256 >&datos
    rm -rf lattice* f* g* h* T* U*  rho* *.case

    cd ../32
    ln -s ../../../InitialParameters.txt .
    latticeBox2D 3 32 periodicX
    cudaVdWColumnHT 50000 50100 256 >&datos
    rm -rf lattice* f* g* h* T* U*  rho* *.case

    cd ../64
    ln -s ../../../InitialParameters.txt .
    latticeBox2D 3 64 periodicX
    cudaVdWColumnHT 50000 50100 256 >&datos
    rm -rf lattice* f* g* h* T* U*  rho* *.case

    cd ../128
    ln -s ../../../InitialParameters.txt .
    latticeBox2D 3 128 periodicX
    cudaVdWColumnHT 50000 50100 256 >&datos
    rm -rf lattice* f* g* h* T* U*  rho* *.case

    cd ../256
    ln -s ../../../InitialParameters.txt .
    latticeBox2D 3 256 periodicX
    cudaVdWColumnHT 50000 50100 256 >&datos
    rm -rf lattice* f* g* h* T* U*  rho* *.case

    cd ../512
    ln -s ../../../InitialParameters.txt .
    latticeBox2D 3 512 periodicX
    cudaVdWColumnHT 50000 50100 256 >&datos
    rm -rf lattice* f* g* h* T* U*  rho* *.case

    cd ../1024
    ln -s ../../../InitialParameters.txt .
    latticeBox2D 3 1024 periodicX
    cudaVdWColumnHT 50000 50100 256 >&datos
    rm -rf lattice* f* g* h* T* U*  rho* *.case

    cd ../2048
    ln -s ../../../InitialParameters.txt .
    latticeBox2D 3 2048 periodicX
    cudaVdWColumnHT 50000 50100 256 >&datos
    rm -rf lattice* f* g* h* T* U*  rho* *.case

    cd ../4096
    ln -s ../../../InitialParameters.txt .
    latticeBox2D 3 4096 periodicX
    cudaVdWColumnHT 50000 50100 256 >&datos
    rm -rf lattice* f* g* h* T* U*  rho* *.case

    # Posicionamiento en cuda
    cd ../../

}

echo Done Block

cd 512B

{
    # Creacion de carpetas para el tamaño de bloque
    # Sólo quedará el archivo con el tiempo

    mkdir 16 32 64 128 256 512 1024 2048 4096

    cd 16
    ln -s ../../../InitialParameters.txt .
    latticeBox2D 3 16 periodicX
    cudaVdWColumnHT 50000 50100 512 >&datos
    rm -rf lattice* f* g* h* T* U*  rho* *.case

    cd ../32
    ln -s ../../../InitialParameters.txt .
    latticeBox2D 3 32 periodicX
    cudaVdWColumnHT 50000 50100 512 >&datos
    rm -rf lattice* f* g* h* T* U*  rho* *.case

    cd ../64
    ln -s ../../../InitialParameters.txt .
    latticeBox2D 3 64 periodicX
    cudaVdWColumnHT 50000 50100 512 >&datos
    rm -rf lattice* f* g* h* T* U*  rho* *.case

    cd ../128
    ln -s ../../../InitialParameters.txt .
    latticeBox2D 3 128 periodicX
    cudaVdWColumnHT 50000 50100 512 >&datos
    rm -rf lattice* f* g* h* T* U*  rho* *.case

    cd ../256
    ln -s ../../../InitialParameters.txt .
    latticeBox2D 3 256 periodicX
    cudaVdWColumnHT 50000 50100 512 >&datos
    rm -rf lattice* f* g* h* T* U*  rho* *.case

    cd ../512
    ln -s ../../../InitialParameters.txt .
    latticeBox2D 3 512 periodicX
    cudaVdWColumnHT 50000 50100 512 >&datos
    rm -rf lattice* f* g* h* T* U*  rho* *.case

    cd ../1024
    ln -s ../../../InitialParameters.txt .
    latticeBox2D 3 1024 periodicX
    cudaVdWColumnHT 50000 50100 512 >&datos
    rm -rf lattice* f* g* h* T* U*  rho* *.case

    cd ../2048
    ln -s ../../../InitialParameters.txt .
    latticeBox2D 3 2048 periodicX
    cudaVdWColumnHT 50000 50100 512 >&datos
    rm -rf lattice* f* g* h* T* U*  rho* *.case

    cd ../4096
    ln -s ../../../InitialParameters.txt .
    latticeBox2D 3 4096 periodicX
    cudaVdWColumnHT 50000 50100 512 >&datos
    rm -rf lattice* f* g* h* T* U*  rho* *.case

    # Posicionamiento en cuda
    cd ../../

}

echo Done Block
# Posicionamiento en sUpMxC
cd ../

# Copia de datos a una carpeta externa de LBCUDA_Test

cp -r cuda ../../../speedUp_cudaVdW

