#!/bin/bash

#Tamaño de la grilla

cd ../../../../

mkdir speedUp_cudaMxC

cd speedUp_cudaMxC

cp ../LBCUDA_Test/validation_speed_up/sUpMxC/InitialParameters.txt .

mkdir 16 32 64 128 256 512 1024 2048 4096

#--------------------------------------------------------------------

cd 16

latticeBox2D 16 16 periodicXY
mkdir 1B 2B 4B 8B 16B 32B 64B 128B 256B 512B

#Entrar a los bloques
cd 1B

ln -s ../lattice/ .
ln -s ../../InitialParameters.txt .
cudaMaxwellConstruction 50000 50100 1 >&datos
rm -rf l* f* g* U* r* T*  h* I*
cd ../

cd 2B

ln -s ../lattice/ .
ln -s ../../InitialParameters.txt .
cudaMaxwellConstruction 50000 50100 2 >&datos
rm -rf l* f* g* U* r* T*  h* I*
cd ../

cd 4B

ln -s ../lattice/ .
ln -s ../../InitialParameters.txt .
cudaMaxwellConstruction 50000 50100 4 >&datos
rm -rf l* f* g* U* r* T*  h* I*
cd ../

cd 8B

ln -s ../lattice/ .
ln -s ../../InitialParameters.txt .
cudaMaxwellConstruction 50000 50100 8 >&datos
rm -rf l* f* g* U* r* T*  h* I*
cd ../

cd 16B

ln -s ../lattice/ .
ln -s ../../InitialParameters.txt .
cudaMaxwellConstruction 50000 50100 16 >&datos
rm -rf l* f* g* U* r* T*  h* I*
cd ../

cd 32B

ln -s ../lattice/ .
ln -s ../../InitialParameters.txt .
cudaMaxwellConstruction 50000 50100 32 >&datos
rm -rf l* f* g* U* r* T*  h* I*
cd ../

cd 64B

ln -s ../lattice/ .
ln -s ../../InitialParameters.txt .
cudaMaxwellConstruction 50000 50100 64 >&datos
rm -rf l* f* g* U* r* T*  h* I*
cd ../

cd 128B

ln -s ../lattice/ .
ln -s ../../InitialParameters.txt .
cudaMaxwellConstruction 50000 50100 128 >&datos
rm -rf l* f* g* U* r* T*  h* I*
cd ../

cd 256B

ln -s ../lattice/ .
ln -s ../../InitialParameters.txt .
cudaMaxwellConstruction 50000 50100 256 >&datos
rm -rf l* f* g* U* r* T*  h* I*
cd ../

cd 512B

ln -s ../lattice/ .
ln -s ../../InitialParameters.txt .
cudaMaxwellConstruction 50000 50100 512 >&datos
rm -rf l* f* g* U* r* T*  h* I*
cd ../

#---##
rm -rf lattice/
cd ../
#---##

#--------------------------------------------------------------------

cd 32

latticeBox2D 32 32 periodicXY
mkdir 1B 2B 4B 8B 16B 32B 64B 128B 256B 512B

#Entrar a los bloques
cd 1B

ln -s ../lattice/ .
ln -s ../../InitialParameters.txt .
cudaMaxwellConstruction 50000 50100 1 >&datos
rm -rf l* f* g* U* r* T*  h* I*
cd ../

cd 2B

ln -s ../lattice/ .
ln -s ../../InitialParameters.txt .
cudaMaxwellConstruction 50000 50100 2 >&datos
rm -rf l* f* g* U* r* T*  h* I*
cd ../

cd 4B

ln -s ../lattice/ .
ln -s ../../InitialParameters.txt .
cudaMaxwellConstruction 50000 50100 4 >&datos
rm -rf l* f* g* U* r* T*  h* I*
cd ../

cd 8B

ln -s ../lattice/ .
ln -s ../../InitialParameters.txt .
cudaMaxwellConstruction 50000 50100 8 >&datos
rm -rf l* f* g* U* r* T*  h* I*
cd ../

cd 16B

ln -s ../lattice/ .
ln -s ../../InitialParameters.txt .
cudaMaxwellConstruction 50000 50100 16 >&datos
rm -rf l* f* g* U* r* T*  h* I*
cd ../

cd 32B

ln -s ../lattice/ .
ln -s ../../InitialParameters.txt .
cudaMaxwellConstruction 50000 50100 32 >&datos
rm -rf l* f* g* U* r* T*  h* I*
cd ../

cd 64B

ln -s ../lattice/ .
ln -s ../../InitialParameters.txt .
cudaMaxwellConstruction 50000 50100 64 >&datos
rm -rf l* f* g* U* r* T*  h* I*
cd ../

cd 128B

ln -s ../lattice/ .
ln -s ../../InitialParameters.txt .
cudaMaxwellConstruction 50000 50100 128 >&datos
rm -rf l* f* g* U* r* T*  h* I*
cd ../

cd 256B

ln -s ../lattice/ .
ln -s ../../InitialParameters.txt .
cudaMaxwellConstruction 50000 50100 256 >&datos
rm -rf l* f* g* U* r* T*  h* I*
cd ../

cd 512B

ln -s ../lattice/ .
ln -s ../../InitialParameters.txt .
cudaMaxwellConstruction 50000 50100 512 >&datos
rm -rf l* f* g* U* r* T*  h* I*
cd ../

#---##
rm -rf lattice/
cd ../
#---##

#--------------------------------------------------------------------

cd 64

latticeBox2D 64 64 periodicXY
mkdir 1B 2B 4B 8B 16B 32B 64B 128B 256B 512B

#Entrar a los bloques
cd 1B

ln -s ../lattice/ .
ln -s ../../InitialParameters.txt .
cudaMaxwellConstruction 50000 50100 1 >&datos
rm -rf l* f* g* U* r* T*  h* I*
cd ../

cd 2B

ln -s ../lattice/ .
ln -s ../../InitialParameters.txt .
cudaMaxwellConstruction 50000 50100 2 >&datos
rm -rf l* f* g* U* r* T*  h* I*
cd ../

cd 4B

ln -s ../lattice/ .
ln -s ../../InitialParameters.txt .
cudaMaxwellConstruction 50000 50100 4 >&datos
rm -rf l* f* g* U* r* T*  h* I*
cd ../

cd 8B

ln -s ../lattice/ .
ln -s ../../InitialParameters.txt .
cudaMaxwellConstruction 50000 50100 8 >&datos
rm -rf l* f* g* U* r* T*  h* I*
cd ../

cd 16B

ln -s ../lattice/ .
ln -s ../../InitialParameters.txt .
cudaMaxwellConstruction 50000 50100 16 >&datos
rm -rf l* f* g* U* r* T*  h* I*
cd ../

cd 32B

ln -s ../lattice/ .
ln -s ../../InitialParameters.txt .
cudaMaxwellConstruction 50000 50100 32 >&datos
rm -rf l* f* g* U* r* T*  h* I*
cd ../

cd 64B

ln -s ../lattice/ .
ln -s ../../InitialParameters.txt .
cudaMaxwellConstruction 50000 50100 64 >&datos
rm -rf l* f* g* U* r* T*  h* I*
cd ../

cd 128B

ln -s ../lattice/ .
ln -s ../../InitialParameters.txt .
cudaMaxwellConstruction 50000 50100 128 >&datos
rm -rf l* f* g* U* r* T*  h* I*
cd ../

cd 256B

ln -s ../lattice/ .
ln -s ../../InitialParameters.txt .
cudaMaxwellConstruction 50000 50100 256 >&datos
rm -rf l* f* g* U* r* T*  h* I*
cd ../

cd 512B

ln -s ../lattice/ .
ln -s ../../InitialParameters.txt .
cudaMaxwellConstruction 50000 50100 512 >&datos
rm -rf l* f* g* U* r* T*  h* I*
cd ../

#---##
rm -rf lattice/
cd ../
#---##

#--------------------------------------------------------------------

cd 128

latticeBox2D 128 128 periodicXY
mkdir 1B 2B 4B 8B 16B 32B 64B 128B 256B 512B

#Entrar a los bloques
cd 1B

ln -s ../lattice/ .
ln -s ../../InitialParameters.txt .
cudaMaxwellConstruction 50000 50100 1 >&datos
rm -rf l* f* g* U* r* T*  h* I*
cd ../

cd 2B

ln -s ../lattice/ .
ln -s ../../InitialParameters.txt .
cudaMaxwellConstruction 50000 50100 2 >&datos
rm -rf l* f* g* U* r* T*  h* I*
cd ../

cd 4B

ln -s ../lattice/ .
ln -s ../../InitialParameters.txt .
cudaMaxwellConstruction 50000 50100 4 >&datos
rm -rf l* f* g* U* r* T*  h* I*
cd ../

cd 8B

ln -s ../lattice/ .
ln -s ../../InitialParameters.txt .
cudaMaxwellConstruction 50000 50100 8 >&datos
rm -rf l* f* g* U* r* T*  h* I*
cd ../

cd 16B

ln -s ../lattice/ .
ln -s ../../InitialParameters.txt .
cudaMaxwellConstruction 50000 50100 16 >&datos
rm -rf l* f* g* U* r* T*  h* I*
cd ../

cd 32B

ln -s ../lattice/ .
ln -s ../../InitialParameters.txt .
cudaMaxwellConstruction 50000 50100 32 >&datos
rm -rf l* f* g* U* r* T*  h* I*
cd ../

cd 64B

ln -s ../lattice/ .
ln -s ../../InitialParameters.txt .
cudaMaxwellConstruction 50000 50100 64 >&datos
rm -rf l* f* g* U* r* T*  h* I*
cd ../

cd 128B

ln -s ../lattice/ .
ln -s ../../InitialParameters.txt .
cudaMaxwellConstruction 50000 50100 128 >&datos
rm -rf l* f* g* U* r* T*  h* I*
cd ../

cd 256B

ln -s ../lattice/ .
ln -s ../../InitialParameters.txt .
cudaMaxwellConstruction 50000 50100 256 >&datos
rm -rf l* f* g* U* r* T*  h* I*
cd ../

cd 512B

ln -s ../lattice/ .
ln -s ../../InitialParameters.txt .
cudaMaxwellConstruction 50000 50100 512 >&datos
rm -rf l* f* g* U* r* T*  h* I*
cd ../

#---##
rm -rf lattice/
cd ../
#---##

#--------------------------------------------------------------------

cd 256

latticeBox2D 256 256 periodicXY
mkdir 1B 2B 4B 8B 16B 32B 64B 128B 256B 512B

#Entrar a los bloques
cd 1B

ln -s ../lattice/ .
ln -s ../../InitialParameters.txt .
cudaMaxwellConstruction 50000 50100 1 >&datos
rm -rf l* f* g* U* r* T*  h* I*
cd ../

cd 2B

ln -s ../lattice/ .
ln -s ../../InitialParameters.txt .
cudaMaxwellConstruction 50000 50100 2 >&datos
rm -rf l* f* g* U* r* T*  h* I*
cd ../

cd 4B

ln -s ../lattice/ .
ln -s ../../InitialParameters.txt .
cudaMaxwellConstruction 50000 50100 4 >&datos
rm -rf l* f* g* U* r* T*  h* I*
cd ../

cd 8B

ln -s ../lattice/ .
ln -s ../../InitialParameters.txt .
cudaMaxwellConstruction 50000 50100 8 >&datos
rm -rf l* f* g* U* r* T*  h* I*
cd ../

cd 16B

ln -s ../lattice/ .
ln -s ../../InitialParameters.txt .
cudaMaxwellConstruction 50000 50100 16 >&datos
rm -rf l* f* g* U* r* T*  h* I*
cd ../

cd 32B

ln -s ../lattice/ .
ln -s ../../InitialParameters.txt .
cudaMaxwellConstruction 50000 50100 32 >&datos
rm -rf l* f* g* U* r* T*  h* I*
cd ../

cd 64B

ln -s ../lattice/ .
ln -s ../../InitialParameters.txt .
cudaMaxwellConstruction 50000 50100 64 >&datos
rm -rf l* f* g* U* r* T*  h* I*
cd ../

cd 128B

ln -s ../lattice/ .
ln -s ../../InitialParameters.txt .
cudaMaxwellConstruction 50000 50100 128 >&datos
rm -rf l* f* g* U* r* T*  h* I*
cd ../

cd 256B

ln -s ../lattice/ .
ln -s ../../InitialParameters.txt .
cudaMaxwellConstruction 50000 50100 256 >&datos
rm -rf l* f* g* U* r* T*  h* I*
cd ../

cd 512B

ln -s ../lattice/ .
ln -s ../../InitialParameters.txt .
cudaMaxwellConstruction 50000 50100 512 >&datos
rm -rf l* f* g* U* r* T*  h* I*
cd ../

#---##
rm -rf lattice/
cd ../
#---##

#--------------------------------------------------------------------

cd 512

latticeBox2D 512 512 periodicXY
mkdir 1B 2B 4B 8B 16B 32B 64B 128B 256B 512B

#Entrar a los bloques
cd 1B

ln -s ../lattice/ .
ln -s ../../InitialParameters.txt .
cudaMaxwellConstruction 50000 50100 1 >&datos
rm -rf l* f* g* U* r* T*  h* I*
cd ../

cd 2B

ln -s ../lattice/ .
ln -s ../../InitialParameters.txt .
cudaMaxwellConstruction 50000 50100 2 >&datos
rm -rf l* f* g* U* r* T*  h* I*
cd ../

cd 4B

ln -s ../lattice/ .
ln -s ../../InitialParameters.txt .
cudaMaxwellConstruction 50000 50100 4 >&datos
rm -rf l* f* g* U* r* T*  h* I*
cd ../

cd 8B

ln -s ../lattice/ .
ln -s ../../InitialParameters.txt .
cudaMaxwellConstruction 50000 50100 8 >&datos
rm -rf l* f* g* U* r* T*  h* I*
cd ../

cd 16B

ln -s ../lattice/ .
ln -s ../../InitialParameters.txt .
cudaMaxwellConstruction 50000 50100 16 >&datos
rm -rf l* f* g* U* r* T*  h* I*
cd ../

cd 32B

ln -s ../lattice/ .
ln -s ../../InitialParameters.txt .
cudaMaxwellConstruction 50000 50100 32 >&datos
rm -rf l* f* g* U* r* T*  h* I*
cd ../

cd 64B

ln -s ../lattice/ .
ln -s ../../InitialParameters.txt .
cudaMaxwellConstruction 50000 50100 64 >&datos
rm -rf l* f* g* U* r* T*  h* I*
cd ../

cd 128B

ln -s ../lattice/ .
ln -s ../../InitialParameters.txt .
cudaMaxwellConstruction 50000 50100 128 >&datos
rm -rf l* f* g* U* r* T*  h* I*
cd ../

cd 256B

ln -s ../lattice/ .
ln -s ../../InitialParameters.txt .
cudaMaxwellConstruction 50000 50100 256 >&datos
rm -rf l* f* g* U* r* T*  h* I*
cd ../

cd 512B

ln -s ../lattice/ .
ln -s ../../InitialParameters.txt .
cudaMaxwellConstruction 50000 50100 512 >&datos
rm -rf l* f* g* U* r* T*  h* I*
cd ../

#---##
rm -rf lattice/
cd ../
#---##



#--------------------------------------------------------------------

cd 1024

latticeBox2D 1024 1024 periodicXY

mkdir 1B 2B 4B 8B 16B 32B 64B 128B 256B 512B

#Entrar a los bloques
cd 1B

ln -s ../lattice/ .
ln -s ../../InitialParameters.txt .
cudaMaxwellConstruction 2500 2510 1 >&datos
rm -rf l* f* g* U* r* T*  h* I*
cd ../

cd 2B

ln -s ../lattice/ .
ln -s ../../InitialParameters.txt .
cudaMaxwellConstruction 2500 2510 2 >&datos
rm -rf l* f* g* U* r* T*  h* I*
cd ../

cd 4B

ln -s ../lattice/ .
ln -s ../../InitialParameters.txt .
cudaMaxwellConstruction 2500 2510 4 >&datos
rm -rf l* f* g* U* r* T*  h* I*
cd ../

cd 8B

ln -s ../lattice/ .
ln -s ../../InitialParameters.txt .
cudaMaxwellConstruction 2500 2510 8 >&datos
rm -rf l* f* g* U* r* T*  h* I*
cd ../

cd 16B

ln -s ../lattice/ .
ln -s ../../InitialParameters.txt .
cudaMaxwellConstruction 2500 2510 16 >&datos
rm -rf l* f* g* U* r* T*  h* I*
cd ../

cd 32B

ln -s ../lattice/ .
ln -s ../../InitialParameters.txt .
cudaMaxwellConstruction 2500 2510 32 >&datos
rm -rf l* f* g* U* r* T*  h* I*
cd ../

cd 64B

ln -s ../lattice/ .
ln -s ../../InitialParameters.txt .
cudaMaxwellConstruction 2500 2510 64 >&datos
rm -rf l* f* g* U* r* T*  h* I*
cd ../

cd 128B

ln -s ../lattice/ .
ln -s ../../InitialParameters.txt .
cudaMaxwellConstruction 2500 2510 128 >&datos
rm -rf l* f* g* U* r* T*  h* I*
cd ../

cd 256B

ln -s ../lattice/ .
ln -s ../../InitialParameters.txt .
cudaMaxwellConstruction 2500 2510 256 >&datos
rm -rf l* f* g* U* r* T*  h* I*
cd ../

cd 512B

ln -s ../lattice/ .
ln -s ../../InitialParameters.txt .
cudaMaxwellConstruction 2500 2510 512 >&datos
rm -rf l* f* g* U* r* T*  h* I*
cd ../

#---##
rm -rf lattice/
cd ../
#---##

#--------------------------------------------------------------------
cd 2048

latticeBox2D 2048 2048 periodicXY

mkdir 1B 2B 4B 8B 16B 32B 64B 128B 256B 512B

#Entrar a los bloques
cd 1B

ln -s ../lattice/ .
ln -s ../../InitialParameters.txt .
cudaMaxwellConstruction 2500 2510 1 >&datos
rm -rf l* f* g* U* r* T*  h* I*
cd ../

cd 2B

ln -s ../lattice/ .
ln -s ../../InitialParameters.txt .
cudaMaxwellConstruction 2500 2510 2 >&datos
rm -rf l* f* g* U* r* T*  h* I*
cd ../

cd 4B

ln -s ../lattice/ .
ln -s ../../InitialParameters.txt .
cudaMaxwellConstruction 2500 2510 4 >&datos
rm -rf l* f* g* U* r* T*  h* I*
cd ../

cd 8B

ln -s ../lattice/ .
ln -s ../../InitialParameters.txt .
cudaMaxwellConstruction 2500 2510 8 >&datos
rm -rf l* f* g* U* r* T*  h* I*
cd ../

cd 16B

ln -s ../lattice/ .
ln -s ../../InitialParameters.txt .
cudaMaxwellConstruction 2500 2510 16 >&datos
rm -rf l* f* g* U* r* T*  h* I*
cd ../

cd 32B

ln -s ../lattice/ .
ln -s ../../InitialParameters.txt .
cudaMaxwellConstruction 2500 2510 32 >&datos
rm -rf l* f* g* U* r* T*  h* I*
cd ../

cd 64B

ln -s ../lattice/ .
ln -s ../../InitialParameters.txt .
cudaMaxwellConstruction 2500 2510 64 >&datos
rm -rf l* f* g* U* r* T*  h* I*
cd ../

cd 128B

ln -s ../lattice/ .
ln -s ../../InitialParameters.txt .
cudaMaxwellConstruction 2500 2510 128 >&datos
rm -rf l* f* g* U* r* T*  h* I*
cd ../

cd 256B

ln -s ../lattice/ .
ln -s ../../InitialParameters.txt .
cudaMaxwellConstruction 2500 2510 256 >&datos
rm -rf l* f* g* U* r* T*  h* I*
cd ../

cd 512B

ln -s ../lattice/ .
ln -s ../../InitialParameters.txt .
cudaMaxwellConstruction 2500 2510 512 >&datos
rm -rf l* f* g* U* r* T*  h* I*
cd ../

#---##
rm -rf lattice/
cd ../
#---##

#--------------------------------------------------------------------
cd 4096

latticeBox2D 4096 4096 periodicXY

mkdir 1B 2B 4B 8B 16B 32B 64B 128B 256B 512B

#Entrar a los bloques
cd 1B

ln -s ../lattice/ .
ln -s ../../InitialParameters.txt .
cudaMaxwellConstruction 2500 2510 1 >&datos
rm -rf l* f* g* U* r* T*  h* I*
cd ../

cd 2B

ln -s ../lattice/ .
ln -s ../../InitialParameters.txt .
cudaMaxwellConstruction 2500 2510 2 >&datos
rm -rf l* f* g* U* r* T*  h* I*
cd ../

cd 4B

ln -s ../lattice/ .
ln -s ../../InitialParameters.txt .
cudaMaxwellConstruction 2500 2510 4 >&datos
rm -rf l* f* g* U* r* T*  h* I*
cd ../

cd 8B

ln -s ../lattice/ .
ln -s ../../InitialParameters.txt .
cudaMaxwellConstruction 2500 2510 8 >&datos
rm -rf l* f* g* U* r* T*  h* I*
cd ../

cd 16B

ln -s ../lattice/ .
ln -s ../../InitialParameters.txt .
cudaMaxwellConstruction 2500 2510 16 >&datos
rm -rf l* f* g* U* r* T*  h* I*
cd ../

cd 32B

ln -s ../lattice/ .
ln -s ../../InitialParameters.txt .
cudaMaxwellConstruction 2500 2510 32 >&datos
rm -rf l* f* g* U* r* T*  h* I*
cd ../

cd 64B

ln -s ../lattice/ .
ln -s ../../InitialParameters.txt .
cudaMaxwellConstruction 2500 2510 64 >&datos
rm -rf l* f* g* U* r* T*  h* I*
cd ../

cd 128B

ln -s ../lattice/ .
ln -s ../../InitialParameters.txt .
cudaMaxwellConstruction 2500 2510 128 >&datos
rm -rf l* f* g* U* r* T*  h* I*
cd ../

cd 256B

ln -s ../lattice/ .
ln -s ../../InitialParameters.txt .
cudaMaxwellConstruction 2500 2510 256 >&datos
rm -rf l* f* g* U* r* T*  h* I*
cd ../

cd 512B

ln -s ../lattice/ .
ln -s ../../InitialParameters.txt .
cudaMaxwellConstruction 2500 2510 512 >&datos
rm -rf l* f* g* U* r* T*  h* I*
cd ../

#---##
rm -rf lattice/
cd ../
#---##
