#!/bin/bash

#Tamaño de la grilla

cd ../../../../

mkdir speedUp_VdW

cd speedUp_VdW

cp ../LBCUDA_Test/validation_speed_up/sUpVdW/InitialParameters.txt .

mkdir 3 4 8 16 32 64 128 256 512 1024

#--------------------------------------------------------------------

#Entrar a los bloques

cd 3

latticeBox2D 3 300 periodicXY
ln -s ../InitialParameters.txt .
VdWColumnHT 20000 20100 >&datos
rm -rf l* f* g* U* r* T*  h* I*
cd ../

echo Done 3

cd 4

latticeBox2D 4 300 periodicXY
ln -s ../InitialParameters.txt .
VdWColumnHT 20000 20100 >&datos
rm -rf l* f* g* U* r* T*  h* I*
cd ../

echo Done 4

cd 8

latticeBox2D 8 300 periodicXY
ln -s ../InitialParameters.txt .
VdWColumnHT 20000 20100 >&datos
rm -rf l* f* g* U* r* T*  h* I*
cd ../

echo Done 8

cd 16

latticeBox2D 16 300 periodicXY
ln -s ../InitialParameters.txt .
VdWColumnHT 20000 20100 >&datos
rm -rf l* f* g* U* r* T*  h* I*
cd ../

echo Done 16

cd 32

latticeBox2D 32 300 periodicXY
ln -s ../InitialParameters.txt .
VdWColumnHT 20000 20100 >&datos
rm -rf l* f* g* U* r* T*  h* I*
cd ../

echo Done 32

cd 64

latticeBox2D 64 300 periodicXY
ln -s ../InitialParameters.txt .
VdWColumnHT 20000 20100 >&datos
rm -rf l* f* g* U* r* T*  h* I*
cd ../

echo Done 64

cd 128

latticeBox2D 128 300 periodicXY
ln -s ../InitialParameters.txt .
VdWColumnHT 20000 20100 >&datos
rm -rf l* f* g* U* r* T*  h* I*
cd ../

echo Done 128

cd 256

latticeBox2D 256 300 periodicXY
ln -s ../InitialParameters.txt .
VdWColumnHT 20000 20100 >&datos
rm -rf l* f* g* U* r* T*  h* I*
cd ../

echo Done 256

cd 512

latticeBox2D 512 300 periodicXY
ln -s ../InitialParameters.txt .
VdWColumnHT 20000 20100 >&datos
rm -rf l* f* g* U* r* T*  h* I*
cd ../

echo Done 512

cd 1024

latticeBox2D 1024 300 periodicXY
ln -s ../InitialParameters.txt .
VdWColumnHT 20000 20100 >&datos
rm -rf l* f* g* U* r* T*  h* I*
cd ../

echo Done 1024


