#!/bin/bash

# generacion de datos para validarlos en C de la Construccion de Maxwell

cd ../../sUpVdW

# ingresando a la construcción en c
cd c

# inicio de generacion de datos
{
    mkdir 16 32 64 128 256 512 1024 2048 4096

    cd 16
    ln -s ../../InitialParameters.txt .
    latticeBox2D 3 16 periodicX
    VdWColumnHT 50000 50100 >&datos
    rm -rf lattice* f* g* h* T* U*  rho* *.case

    cd ../32
    ln -s ../../InitialParameters.txt .
    latticeBox2D 3 32 periodicX
    VdWColumnHT 50000 50100 >&datos
    rm -rf lattice* f* g* h* T* U*  rho* *.case

    cd ../64
    ln -s ../../InitialParameters.txt .
    latticeBox2D 3 64 periodicX
    VdWColumnHT 50000 50100 >&datos
    rm -rf lattice* f* g* h* T* U*  rho* *.case

    cd ../128
    ln -s ../../InitialParameters.txt .
    latticeBox2D 3 128 periodicX
    VdWColumnHT 50000 50100 >&datos
    rm -rf lattice* f* g* h* T* U*  rho* *.case

    cd ../256
    ln -s ../../InitialParameters.txt .
    latticeBox2D 3 256 periodicX
    VdWColumnHT 50000 50100 >&datos
    rm -rf lattice* f* g* h* T* U*  rho* *.case

    cd ../512
    ln -s ../../InitialParameters.txt .
    latticeBox2D 3 512 periodicX
    VdWColumnHT 50000 50100 >&datos
    rm -rf lattice* f* g* h* T* U*  rho* *.case

    cd ../1024
    ln -s ../../InitialParameters.txt .
    latticeBox2D 3 1024 periodicX
    VdWColumnHT 50000 50100 >&datos
    rm -rf lattice* f* g* h* T* U*  rho* *.case

    cd ../2048
    ln -s ../../InitialParameters.txt .
    latticeBox2D 3 2048 periodicX
    VdWColumnHT 50000 50100 >&datos
    rm -rf lattice* f* g* h* T* U*  rho* *.case

    cd ../4096
    ln -s ../../InitialParameters.txt .
    latticeBox2D 3 4096 periodicX
    VdWColumnHT 50000 50100 >&datos
    rm -rf lattice* f* g* h* T* U*  rho* *.case

    
}

# Posicionamiento en valMxC
cd ../../

# Copia de datos a una carpeta externa de LBCUDA_Test

cp -r c ../../../speedUp_VdW

