#!/bin/bash

# Limpieza de datos de validarlos en C de VdWcolumnHT

cd ../../valVdW

rm -rf lattice

cd c

# Limpieza de datos

cd 6
rm -rf l* d* r* U* time_e*  f* g* T* h*

cd ../625
rm -rf l* d* r* U* time_e*  f* g* T* h*

cd ../65
rm -rf l* d* r* U* time_e*  f* g* T* h*

cd ../675
rm -rf l* d* r* U* time_e*  f* g* T* h*

cd ../7
rm -rf l* d* r* U* time_e*  f* g* T* h*

cd ../725
rm -rf l* d* r* U* time_e*  f* g* T* h*

cd ../75
rm -rf l* d* r* U* time_e*  f* g* T* h*

cd ../775
rm -rf l* d* r* U* time_e*  f* g* T* h*

cd ../8
rm -rf l* d* r* U* time_e*  f* g* T* h*

cd ../825
rm -rf l* d* r* U* time_e*  f* g* T* h*

cd ../85
rm -rf l* d* r* U* time_e*  f* g* T* h*

cd ../875
rm -rf l* d* r* U* time_e*  f* g* T* h*

cd ../9
rm -rf l* d* r* U* time_e*  f* g* T* h*

cd ../925
rm -rf l* d* r* U* time_e*  f* g* T* h*

cd ../95
rm -rf l* d* r* U* time_e*  f* g* T* h*

cd ../975
rm -rf l* d* r* U* time_e*  f* g* T* h*

