#!/bin/bash

# generacion de datos para validarlos en C de la Construccion de Maxwell

cd ../../valMxC

latticeBox2D 100 100 periodicXY

# ingresando a la construcción en c
cd cuda

# inicio de generacion de datos
{
    cd 6
    ln -s ../../lattice/ .
    cudaMaxwellConstruction 100000 100000 128 >&datos

    cd ../625
    ln -s ../../lattice/ .
    cudaMaxwellConstruction 100000 100000 128 >&datos

    cd ../65
    ln -s ../../lattice/ .
    cudaMaxwellConstruction 100000 100000 128 >&datos

    cd ../675
    ln -s ../../lattice/ .
    cudaMaxwellConstruction 100000 100000 128 >&datos

    cd ../7
    ln -s ../../lattice/ .
    cudaMaxwellConstruction 100000 100000 128 >&datos

    cd ../725
    ln -s ../../lattice/ .
    cudaMaxwellConstruction 100000 100000 128 >&datos

    cd ../75
    ln -s ../../lattice/ .
    cudaMaxwellConstruction 100000 100000 128 >&datos

    cd ../775
    ln -s ../../lattice/ .
    cudaMaxwellConstruction 100000 100000 128 >&datos

    cd ../8
    ln -s ../../lattice/ .
    cudaMaxwellConstruction 100000 100000 128 >&datos

    cd ../825
    ln -s ../../lattice/ .
    cudaMaxwellConstruction 100000 100000 128 >&datos

    cd ../85
    ln -s ../../lattice/ .
    cudaMaxwellConstruction 100000 100000 128 >&datos

    cd ../875
    ln -s ../../lattice/ .
    cudaMaxwellConstruction 100000 100000 128 >&datos

    cd ../9
    ln -s ../../lattice/ .
    cudaMaxwellConstruction 100000 100000 128 >&datos

    cd ../925
    ln -s ../../lattice/ .
    cudaMaxwellConstruction 100000 100000 128 >&datos

    cd ../95
    ln -s ../../lattice/ .
    cudaMaxwellConstruction 100000 100000 128 >&datos

    cd ../975
    ln -s ../../lattice/ .
    cudaMaxwellConstruction 100000 100000 128 >&datos
}

# Posicionamiento en valMxC
cd ../../

# Copia de datos a una carpeta externa de LBCUDA_Test

cp -r c ../../../validacion_cudaMxC

