#!/bin/bash

# generacion de datos para validarlos en C de la Construccion de Maxwell

cd ../../valVdW

# Copia de los parámetros para realizar el muestreo

cp -r cuda ../../../validacion_VdW

# Ingresando a realizar la estratificación de Maxwell en C

cd ../../../validacion_cudaVdW

# Generacion de la grilla

latticeBox2D 3 300 periodicX

# inicio de generacion de datos
{
    cd 6
    ln -s ../lattice/ .
    cudaVdWColumnHT 750000 750000 128 >&datos

    cd ../625
    ln -s ../lattice/ .
    cudaVdWColumnHT 750000 750000 128 >&datos

    cd ../65
    ln -s ../lattice/ .
    cudaVdWColumnHT 750000 750000 128 >&datos

    cd ../675
    ln -s ../lattice/ .
    cudaVdWColumnHT 750000 750000 128 >&datos

    cd ../7
    ln -s ../lattice/ .
    cudaVdWColumnHT 750000 750000 128 >&datos

    cd ../725
    ln -s ../lattice/ .
    cudaVdWColumnHT 750000 750000 128 >&datos

    cd ../75
    ln -s ../lattice/ .
    cudaVdWColumnHT 750000 750000 128 >&datos

    cd ../775
    ln -s ../lattice/ .
    cudaVdWColumnHT 750000 750000 128 >&datos

    cd ../8
    ln -s ../lattice/ .
    cudaVdWColumnHT 750000 750000 128 >&datos

    cd ../825
    ln -s ../lattice/ .
    cudaVdWColumnHT 750000 750000 128 >&datos

    cd ../85
    ln -s ../lattice/ .
    cudaVdWColumnHT 750000 750000 128 >&datos

    cd ../875
    ln -s ../lattice/ .
    cudaVdWColumnHT 750000 750000 128 >&datos

    cd ../9
    ln -s ../lattice/ .
    cudaVdWColumnHT 750000 750000 128 >&datos

    cd ../925
    ln -s ../lattice/ .
    cudaVdWColumnHT 750000 750000 128 >&datos

    cd ../95
    ln -s ../lattice/ .
    cudaVdWColumnHT 750000 750000 128 >&datos

    cd ../975
    ln -s ../lattice/ .
    cudaVdWColumnHT 750000 750000 128 >&datos
}
