#!/bin/bash

# generacion de datos para validarlos en C de la Construccion de Maxwell

cd ../../valVdW

latticeBox2D 3 300 periodicX

# ingresando a cuda
cd cuda

# inicio de generacion de datos
{
    cd 6
    ln -s ../../lattice/ .
    cudaVdWColumnHT 750000 750000 >&datos

    cd ../625
    ln -s ../../lattice/ .
    cudaVdWColumnHT 750000 750000 >&datos

    cd ../65
    ln -s ../../lattice/ .
    cudaVdWColumnHT 750000 750000 >&datos

    cd ../675
    ln -s ../../lattice/ .
    cudaVdWColumnHT 750000 750000 >&datos

    cd ../7
    ln -s ../../lattice/ .
    cudaVdWColumnHT 750000 750000 >&datos

    cd ../725
    ln -s ../../lattice/ .
    cudaVdWColumnHT 750000 750000 >&datos

    cd ../75
    ln -s ../../lattice/ .
    cudaVdWColumnHT 750000 750000 >&datos

    cd ../775
    ln -s ../../lattice/ .
    cudaVdWColumnHT 750000 750000 >&datos

    cd ../8
    ln -s ../../lattice/ .
    cudaVdWColumnHT 750000 750000 >&datos

    cd ../825
    ln -s ../../lattice/ .
    cudaVdWColumnHT 750000 750000 >&datos

    cd ../85
    ln -s ../../lattice/ .
    cudaVdWColumnHT 750000 750000 >&datos

    cd ../875
    ln -s ../../lattice/ .
    cudaVdWColumnHT 750000 750000 >&datos

    cd ../9
    ln -s ../../lattice/ .
    cudaVdWColumnHT 750000 750000 >&datos

    cd ../925
    ln -s ../../lattice/ .
    cudaVdWColumnHT 750000 750000 >&datos

    cd ../95
    ln -s ../../lattice/ .
    cudaVdWColumnHT 750000 750000 >&datos

    cd ../975
    ln -s ../../lattice/ .
    cudaVdWColumnHT 750000 750000 >&datos
}

# Posicionamiento en valVdW
cd ../../

# Copia de datos a una carpeta externa de LBCUDA_Test

cp -r c ../../../validacion_cudaVdW

