#!/bin/bash

# generacion de datos para validarlos en C de la Construccion de Maxwell

cd ../../valMxC

# Copia de los parámetros para realizar el muestreo

cp -r c ../../../validacion_MxC

# Ingresando a realizar la construcción en C

cd ../../../validacion_MxC

# Generacion de la grilla

latticeBox2D 201 201 periodicXY

# inicio de generacion de datos
{
    cd 6
    ln -s ../lattice/ .
    maxwellConstruction 100000 100000 >&datos

    cd ../625
    ln -s ../lattice/ .
    maxwellConstruction 100000 100000 >&datos

    cd ../65
    ln -s ../lattice/ .
    maxwellConstruction 100000 100000 >&datos

    cd ../675
    ln -s ../lattice/ .
    maxwellConstruction 100000 100000 >&datos

    cd ../7
    ln -s ../lattice/ .
    maxwellConstruction 100000 100000 >&datos

    cd ../725
    ln -s ../lattice/ .
    maxwellConstruction 100000 100000 >&datos

    cd ../75
    ln -s ../lattice/ .
    maxwellConstruction 100000 100000 >&datos

    cd ../775
    ln -s ../lattice/ .
    maxwellConstruction 100000 100000 >&datos

    cd ../8
    ln -s ../lattice/ .
    maxwellConstruction 100000 100000 >&datos

    cd ../825
    ln -s ../lattice/ .
    maxwellConstruction 100000 100000 >&datos

    cd ../85
    ln -s ../lattice/ .
    maxwellConstruction 100000 100000 >&datos

    cd ../875
    ln -s ../lattice/ .
    maxwellConstruction 100000 100000 >&datos

    cd ../9
    ln -s ../lattice/ .
    maxwellConstruction 100000 100000 >&datos

    cd ../925
    ln -s ../lattice/ .
    maxwellConstruction 100000 100000 >&datos

    cd ../95
    ln -s ../lattice/ .
    maxwellConstruction 100000 100000 >&datos

    cd ../975
    ln -s ../lattice/ .
    maxwellConstruction 100000 100000 >&datos
}
